First we import all necessary packages

In [145]:
from pandas import read_stata
import numpy as np
import pandas as pd
from sklearn import linear_model
from numpy import mean

Then we upload the nsw data

In [146]:
nsw = read_stata('nsw.dta')

We add the column age squarred, as we will need the values for our regression

In [147]:
# nsw['agesq'] = nsw['age']** Does not work -> wrong values
# alternative way
a = nsw.values
b = a[:,2]
c = b**2
nsw['agesq'] = c

Now we divide the data into the treatment group and the comparison group. We call the dataframe with the treatment group data nswt and the dataframe for the comparison group data nswc

In [148]:
nswt = nsw[:297] 
nswc = nsw[297:]

We calculate the average values of the treatment groups characteristics that we will need in the regression

In [149]:
nswtage = mean(nswt.age)
nswtedu = mean(nswt.education)
nswtbla = mean(nswt.black)
nswthis = mean(nswt.hispanic)
nswtnod = mean(nswt.nodegree)
nswtasq = mean(nswt.agesq)
nswtre75 = mean(nswt.re75)
nswtre78 = mean(nswt.re78)

Now we can make a regression for the nsw control group, with salary in 1975 as dependent variable. Our independet variables are age, years of schooing, race, highschool dropout status and age squarred.

In [150]:
regnsw = linear_model.LinearRegression()
regnsw.fit(nswc[['age', 'education','black', 'hispanic', 'nodegree', 'agesq']],nswc.re75)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

We insert the average values of the treatment group into the regression.

In [151]:
regnsw.predict([[nswtage, nswtedu, nswtbla, nswthis, nswtnod, nswtasq]])

array([3140.63123988])

The last step is to subtract the estimated salary from the average salary of the treatment group

In [152]:
nswtre75 - 3066

0.09765625

The result is 0 Dollars, while the result of Lalonde is -21 Dollars

We repeat these steps for the psid and cps comparison groups

In [153]:
psid1 = pd.read_stata('psid_controls.dta')

In [154]:
psid1['agesq'] = psid1['age']**2 #Here it works

In [155]:
regpsid1 = linear_model.LinearRegression()
regpsid1.fit(psid1[['age', 'education','black', 'hispanic', 'nodegree', 'agesq']],psid1.re75)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [156]:
regpsid1.predict([[nswtage, nswtedu, nswtbla, nswthis, nswtnod, nswtasq]])

array([9729.41171487])

In [157]:
nswtre75 - 9729

-6662.90234375

Lalondes result is -7624

In [158]:
psid3 = pd.read_stata('psid_controls3.dta')

In [159]:
psid3['agesq'] = psid3['age']**2

In [160]:
regpsid3 = linear_model.LinearRegression()
regpsid3.fit(psid3[['age', 'education','black', 'hispanic', 'nodegree', 'agesq']],psid3.re75)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [161]:
regpsid3.predict([[nswtage, nswtedu, nswtbla, nswthis, nswtnod, nswtasq]])

array([2360.49237568])

In [162]:
nswtre75 - 2360

706.09765625

Lalondes result is 455

In [163]:
cps1 = read_stata('cps_controls.dta')

In [164]:
cps1['agesq'] = cps1['age']**2

In [165]:
regcps1 = linear_model.LinearRegression()
regcps1.fit(cps1[['age', 'education','black', 'hispanic', 'nodegree', 'agesq']],cps1.re75)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [166]:
nswtre75-regcps1.predict([[nswtage, nswtedu, nswtbla, nswthis, nswtnod, nswtasq]])

array([-4596.70246764])

Lalondes result is -4654

In [167]:
cps2 = read_stata('cps_controls2.dta')

In [168]:
cps2['agesq'] = cps2['age']**2

In [169]:
regcps2 = linear_model.LinearRegression()
regcps2.fit(cps2[['age', 'education','black', 'hispanic', 'nodegree', 'agesq']],cps2.re75)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [170]:
nswtre75-regcps2.predict([[nswtage, nswtedu, nswtbla, nswthis, nswtnod, nswtasq]])

array([-2149.02141448])

Lalondes result is -1824

In [171]:
cps3 = read_stata('cps_controls3.dta')

In [172]:
cps3['agesq'] = cps3['age']**2

In [173]:
regcps3 = linear_model.LinearRegression()
regcps3.fit(cps3[['age', 'education','black', 'hispanic', 'nodegree', 'agesq']],cps3.re75)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [174]:
nswtre75-regcps3.predict([[nswtage, nswtedu, nswtbla, nswthis, nswtnod, nswtasq]])

array([771.32178])

Lalondes result is 878